### PR TITLE
core: drop py36 support, update docs for reddit

### PR DESCRIPTION
**Pull request by seanbreckenridge**
This fixes references to the my.reddit module (often used as an example) in the docs/error message/docstrings

### CODE REVIEW

**Comment by seanbreckenridge** [comment]
Seems to be because [pdfannots dropped 3.6 support](https://github.com/0xabu/pdfannots/commits/master)?

**Comment by karlicoss** [comment]
Whoops, sorry, somehow missed the notifications for this! 
Looks good and yeah that's fair, let's drop 3.6. Thanks!

**Comment by seanbreckenridge** [comment]
should I update the docs and the setup.py to bump that to `python_requires='>=3.7'` as well?

**Comment by karlicoss** [comment]
yeah if you don't mind updating other things definitely appreciated!

btw, noticed the python 3.10 commit -- yeah I've run into the same issue I think the other week https://github.com/karlicoss/pockexport/commit/924901fdcdc13c0d9c14d06f68c59b7fbc410bd2 , so I guess for now waiting for that to get fixed

**Comment by seanbreckenridge** [comment]
Seems that the Executor type signature has been updated multiple times and its pretty incompatible across versions

The callable was made a positional only argument, but that [feature isnt available under 3.7](https://www.python.org/dev/peps/pep-0570/), so it just causes a syntax error

I think the easiest thing is to ignore the override for now, and the `#type: ignore[override]` can be removed once `3.7` is at EOL

**Comment by seanbreckenridge** [comment]
I think thats all. Also, I expect this to cause a ripple effect and break anything that installs HPI on 3.6.... [likely need to update this](https://github.com/karlicoss/promnesia/blob/c2d7da626ded5c525c94708273abc245e925cc03/.github/workflows/main.yml#L20)

**Pull request merged**
