### PR TITLE
smscalls: make some fields optional

### PR DESCRIPTION
**Pull request by seanbreckenridge**
reflects the new types-lxml package
https://github.com/abelcheung/types-lxml

### CODE REVIEW

**Comment by seanbreckenridge** [comment]
If you think this is fine, will make a PR to promnesia afterwards to fix the source there

**Comment by karlicoss** [comment]
thanks!

**Comment by karlicoss** [comment]
uhh I should get more sleep :roll_eyes:
Thinking again about it -- is this genuinely the case for smscalls module that these fields can be none? 
If not perhaps best to keep the model stricter and just add asserts to make mypy happy? So the downstream users don't have to handle `None` where it's not really necessary.
Haven't used smscalls for a while so not sure myself.

**Comment by seanbreckenridge** [comment]
yeah, I still use this module

unless the android app changes their format I guess there should never be errors?

so if you prefer I can revert this and instead yield an error if the keys dont exist, that way its stricter

I dont see the sms backup app changing their format after all these years anyways

**Comment by karlicoss** [comment]
Not a huge deal but imo no need to make it optional without a reason. Yielding should be fine, although I guess would require a change in promnesia due to mypy. But perhaps best to always assume modules can yield exception for consistency, so it'll be a useful change anyway :)

**Pull request merged**
